start: 2017-12-02 01:00:03.028000
Traceback (most recent call last):
  File "launcher.py", line 50, in <module>
    execfile(scraper['path'])
  File "C:\users\indisersa\Desktop\hotels\scrapers\marriott_scraper.py", line 142, in <module>
    scrape_dates()
  File "C:\users\indisersa\Desktop\hotels\scrapers\marriott_scraper.py", line 31, in scrape_dates
    scrape_hotel(url, date)
  File "C:\users\indisersa\Desktop\hotels\scrapers\marriott_scraper.py", line 91, in scrape_hotel
    checkin_checkout_scrape(driver, checkin_elms, next_elms)
  File "C:\users\indisersa\Desktop\hotels\scrapers\marriott_scraper.py", line 53, in checkin_checkout_scrape
    next_elements = driver.find_elements_by_xpath(next_els)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 377, in find_elements_by_xpath
    return self.find_elements(by=By.XPATH, value=xpath)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 883, in find_elements
    'value': value})['value'] or []
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: chrome not reachable
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)



Traceback (most recent call last):
  File "launcher.py", line 50, in <module>
    execfile(scraper['path'])
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 98, in <module>
    scrape_dates()
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 38, in scrape_dates
    scrape(url, date)
  File "C:\users\indisersa\Desktop\hotels\scrapers\elconventoantigua_scraper.py", line 72, in scrape
    element_6.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Element is not clickable at point (773, 478)
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)



Traceback (most recent call last):
  File "launcher.py", line 50, in <module>
    execfile(scraper['path'])
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 151, in <module>
    scrape_dates()
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 48, in scrape_dates
    scrape_cities(url, date)
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 52, in scrape_cities
    scrape_city(url, city, date)
  File "C:\users\indisersa\Desktop\hotels\scrapers\book_hotel_beds_scraper.py", line 80, in scrape_city
    checkin_element3.click()
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webelement.py", line 501, in _execute
    return self._parent.execute(command, params)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: unknown error: Element <div class="hcsb_checkinDateWrapper hcsb_clearfix">...</div> is not clickable at point (555, 239). Other element would receive the click: <div id="ui-datepicker-div" class="ui-datepicker ui-widget ui-widget-content ui-helper-clearfix ui-corner-all dp-SB_7ef6e1dfc0" style="margin-top: 25px; position: absolute; top: 0px; left: 563.625px; z-index: 2; display: block;">...</div>
  (Session info: chrome=62.0.3202.94)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 6.1.7601 SP1 x86_64)



Traceback (most recent call last):
  File "launcher.py", line 50, in <module>
    execfile(scraper['path'])
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 200, in <module>
    scrape_dates()
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 98, in scrape_dates
    scrape_cities(url, date)
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 102, in scrape_cities
    scrape_city(url, city, date)
  File "C:\users\indisersa\Desktop\hotels\scrapers\booking_scraper.py", line 115, in scrape_city
    city_element_after = process_elements.visibility(driver, city_element_after, 15)
  File "C:\users\indisersa\Desktop\hotels\scrapers\processors.py", line 18, in visibility
    return WebDriverWait(driver, delay).until(EC.visibility_of_element_located((By.XPATH, element)))
  File "C:\Python27\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
TimeoutException: Message: 



